import{r as i,a as f}from"./assets/header-796fc662.js";import{P as S}from"./assets/vendor-d8b4b001.js";import{r as l}from"./assets/open-exercises-modal-0944e6e4.js";const x="current-exercises-filter-page",p="current-exercises-filter-keyword",L="current-exercises-group-name",u="is-opened-exercises-list",r={checkIsOpenExercisesList:()=>sessionStorage.getItem(u)==="true",openExercisesList:()=>{sessionStorage.setItem(u,"true")},closeExercisesList:()=>{sessionStorage.setItem(u,"false")},exercisesFilters:{set:e=>{sessionStorage.setItem(p,e)},get:()=>sessionStorage.getItem(p)??"Muscles"},exercisesGroups:{set:e=>{sessionStorage.setItem(L,e)},get:()=>sessionStorage.getItem(L)??""},exercisesFiltersTable:{setPage:e=>{sessionStorage.setItem(x,e.toString())},getPage:()=>{const e=sessionStorage.getItem(x);return e?Number(e):1}}},m=()=>{r.openExercisesList(),i.exercisesFiltersList.classList.add("visually-hidden"),i.exercisesFiltersPagination.classList.add("visually-hidden"),i.searchFormElement.classList.remove("visually-hidden"),i.exercisesContainer.classList.remove("visually-hidden")},E=()=>{r.closeExercisesList(),i.exercisesFiltersList.classList.remove("visually-hidden"),i.exercisesFiltersPagination.classList.remove("visually-hidden"),i.searchFormElement.classList.add("visually-hidden"),i.exercisesContainer.classList.add("visually-hidden")},T=r.checkIsOpenExercisesList();T?m():E();const F=({page:e,filter:s})=>f.get(`/filters?page=${e}&filter=${s}`),I=r.exercisesFiltersTable.getPage(),v=r.exercisesFilters.get();C({page:I,filter:v});i.exercisesFiltersTabsList.forEach(e=>{e.textContent.trim()===v&&e.classList.add("active")});function C({page:e,filter:s}){F({page:e,filter:s}).then(({data:{results:t,page:a,perPage:n,totalPages:o}})=>{new S("exercises-filters-pagination",{page:Number(a),itemsPerPage:n,totalItems:o*n}).on("beforeMove",function(g){const w=r.exercisesFilters.get();y(w,g.page),r.exercisesFiltersTable.setPage(g.page)}),h(t)})}function y(e,s){F({page:s,filter:e}).then(({data:t})=>{h(t.results),_()})}function h(e){i.exercisesFiltersList.innerHTML="";const s=e.map(({filter:t,name:a,imgURL:n})=>{const o=`data-filter="${t}"`,c=`data-group="${a}"`;return`
  <li class="filters__item" ${o} ${c}>
    <img class="filters__img-first" src="${n}"  ${o} ${c}></img>
    <div class="filters__wrapper-first" ${o}${c}>
    <h2 class="filters__title-first" ${o} ${c}>${a}</h2>
    <p class="filters__text-first" ${o} ${c}>${t}</p>
    </div>
  </li>
    `}).join("");i.exercisesFiltersList.insertAdjacentHTML("beforeend",s)}i.exercisesFiltersTabs.addEventListener("click",e=>{i.exercisesFiltersTabsList.forEach(t=>{t.classList.remove("active")}),e.target.classList.add("active");const s=e.target.textContent.trim();i.exercisesFiltersList.innerHTML="",E(),r.exercisesFilters.set(s),r.exercisesFiltersTable.setPage(1),C({page:1,filter:s})});function _(){window.scrollTo({top:830,behavior:"auto"})}const d=({filter:e,group:s,keyword:t="",page:a=1})=>{let n=new URLSearchParams({[e]:s,keyword:t,page:a,limit:10});return f.get(`/exercises?${n}`)};async function $(e){e.preventDefault();let s=r.exercisesFilters.get().toLowerCase(),t=r.exercisesGroups.get().toLowerCase();s=s.toLowerCase().split(" ").join(""),s==="bodyparts"&&(s=s.slice(0,-1)),t=t.toLowerCase();const a=e.currentTarget.elements.search.value.trim().toLowerCase()??"",n=await d({filter:s,group:t,keyword:a});l(i.exercisesContainer,n.data.results)}function P(e){if(e.value){e.value="";return}}i.searchClearButton.addEventListener("click",e=>{P(i.searchInputElement);const s=r.exercisesFilters.get().toLowerCase(),t=r.exercisesGroups.get().toLowerCase();d({filter:s,group:t,keyword:""}).then(a=>{l(i.exercisesContainer,a.data.results)})});i.searchFormElement.addEventListener("submit",e=>{$(e)});function b(e,s,t){e.innerText=s,t&&(t.style.visibility="visible")}async function R(e,s,t){const a=await d({filter:s,group:t});b(i.breadcrumbsText,t,i.breadcrumbsDivider),l(e,a.data.results)}i.exercisesFiltersList.addEventListener("click",e=>{let s=e.target.dataset.filter,t=e.target.dataset.group;s=s.toLowerCase().split(" ").join(""),s==="bodyparts"&&(s=s.slice(0,-1)),t=t.toLowerCase(),s&&t&&(m(),r.exercisesGroups.set(t),R(i.exercisesContainer,s,t))});async function k(){let e=r.exercisesFilters.get(),s=r.exercisesGroups.get();e=e.toLowerCase().split(" ").join(""),e==="bodyparts"&&(e=e.slice(0,-1)),s=s.toLowerCase();const t=await d({filter:e,group:s});b(i.breadcrumbsText,s,i.breadcrumbsDivider),l(i.exercisesContainer,t.data.results)}k();
//# sourceMappingURL=commonHelpers2.js.map
