import{r as i,a as L,b as f,c as b}from"./assets/header-d6ee78fb.js";import"./assets/vendor-d8b4b001.js";import"./assets/open-exercises-modal-b96c99e8.js";const u="current-exercises-filter-page",x="current-exercises-filter-keyword",E="current-exercises-group-name",g="is-opened-exercises-list",m="current-exercises-page",p="current-exercises-keyword",r={checkIsOpenExercisesList:()=>sessionStorage.getItem(g)==="true",openExercisesList:()=>{sessionStorage.setItem(g,"true")},closeExercisesList:()=>{sessionStorage.setItem(g,"false")},exercisesFilters:{set:e=>{sessionStorage.setItem(x,e)},get:()=>sessionStorage.getItem(x)??"Muscles"},exercisesGroups:{set:e=>{sessionStorage.setItem(E,e)},get:()=>sessionStorage.getItem(E)??""},exercisesFiltersTable:{setPage:e=>{sessionStorage.setItem(u,e.toString())},getPage:()=>{const e=sessionStorage.getItem(u);return e?Number(e):1}},exercisesTable:{setPage:e=>{sessionStorage.setItem(m,e.toString())},getPage:()=>{const e=sessionStorage.getItem(m);return e?Number(e):1},setKeyword:e=>{sessionStorage.setItem(p,e)},getKeyword:()=>sessionStorage.getItem(p)??""}},v=()=>{r.openExercisesList(),i.exercisesFiltersList.classList.add("visually-hidden"),i.exercisesFiltersPagination.classList.add("visually-hidden"),i.searchFormElement.classList.remove("visually-hidden"),i.exercisesContainer.classList.remove("visually-hidden"),i.mainExercisesPagination.classList.remove("visually-hidden")},T=()=>{r.closeExercisesList(),i.exercisesFiltersList.classList.remove("visually-hidden"),i.exercisesFiltersPagination.classList.remove("visually-hidden"),i.searchFormElement.classList.add("visually-hidden"),i.exercisesContainer.classList.add("visually-hidden"),i.mainExercisesPagination.classList.add("visually-hidden")},_=r.checkIsOpenExercisesList();_?v():T();const F=({page:e,filter:s})=>L.get(`/filters?page=${e}&filter=${s}`),R=r.exercisesFiltersTable.getPage(),y=r.exercisesFilters.get();S({page:R,filter:y});i.exercisesFiltersTabsList.forEach(e=>{e.textContent.trim()===y&&e.classList.add("active")});function S({page:e,filter:s}){F({page:e,filter:s}).then(({data:{results:t,page:a,perPage:o,totalPages:c}})=>{f("exercises-filters-pagination",{page:a,perPage:o,totalPages:c},n=>{const d=r.exercisesFilters.get();$(d,n),r.exercisesFiltersTable.setPage(n)}),h(t)})}function $(e,s){F({page:s,filter:e}).then(({data:t})=>{h(t.results),N()})}function h(e){i.exercisesFiltersList.innerHTML="";const s=e.map(({filter:t,name:a,imgURL:o})=>{const c=`data-filter="${t}"`,n=`data-group="${a}"`;return`
  <li class="filters__item" ${c} ${n}>
    <img class="filters__img-first" src="${o}"  ${c} ${n}></img>
    <div class="filters__wrapper-first" ${c}${n}>
    <h2 class="filters__title-first" ${c} ${n}>${a}</h2>
    <p class="filters__text-first" ${c} ${n}>${t}</p>
    </div>
  </li>
    `}).join("");i.exercisesFiltersList.insertAdjacentHTML("beforeend",s)}i.exercisesFiltersTabs.addEventListener("click",e=>{i.exercisesFiltersTabsList.forEach(t=>{t.classList.remove("active")}),e.target.classList.add("active");const s=e.target.textContent.trim();i.exercisesFiltersList.innerHTML="",T(),r.exercisesFilters.set(s),r.exercisesFiltersTable.setPage(1),r.exercisesTable.setPage(1),S({page:1,filter:s})});function N(){window.scrollTo({top:830,behavior:"auto"})}const C=({filter:e,group:s,keyword:t="",page:a=1})=>{let o=new URLSearchParams({[e]:s,keyword:t,page:a,limit:10});return L.get(`/exercises?${o}`)};function w(e,s,t){e.innerText=s,t&&(t.style.visibility="visible")}async function l(){let e=r.exercisesFilters.get(),s=r.exercisesGroups.get();e=e.toLowerCase().split(" ").join(""),e==="bodyparts"&&(e=e.slice(0,-1)),s=s.toLowerCase();const t=r.exercisesTable.getPage(),a=r.exercisesTable.getKeyword(),o=await C({filter:e,group:s,page:t,keyword:a});w(i.breadcrumbsText,s,i.breadcrumbsDivider);const{results:c,page:n,perPage:d,totalPages:I}=o.data;b(i.exercisesContainer,c),f("main-exercises-pagination",{page:Number(n),perPage:d,totalPages:I},P=>{r.exercisesTable.setPage(P),l()})}l();async function k(e){e.preventDefault();let s=r.exercisesFilters.get().toLowerCase(),t=r.exercisesGroups.get().toLowerCase();s=s.toLowerCase().split(" ").join(""),s==="bodyparts"&&(s=s.slice(0,-1)),t=t.toLowerCase();const a=e.currentTarget.elements.search.value.trim().toLowerCase()??"";r.exercisesTable.setKeyword(a),r.exercisesTable.setPage(1),l()}function K(e){if(e.value){e.value="";return}}i.searchClearButton.addEventListener("click",e=>{K(i.searchInputElement),r.exercisesTable.setKeyword(""),r.exercisesTable.setPage(1),l()});i.searchFormElement.addEventListener("submit",e=>{k(e)});async function D(e,s,t){const a=await C({filter:s,group:t});w(i.breadcrumbsText,t,i.breadcrumbsDivider),b(e,a.data.results)}i.exercisesFiltersList.addEventListener("click",e=>{let s=e.target.dataset.filter,t=e.target.dataset.group;s=s.toLowerCase().split(" ").join(""),s==="bodyparts"&&(s=s.slice(0,-1)),t=t.toLowerCase(),s&&t&&(v(),r.exercisesGroups.set(t),D(i.exercisesContainer,s,t),l())});document.addEventListener("DOMContentLoaded",()=>{const e=r.exercisesTable.getKeyword();i.searchInputElement.value=e??""});
//# sourceMappingURL=commonHelpers2.js.map
