import{r,a as L}from"./assets/header-8a6e6afb.js";import{P as b}from"./assets/vendor-d8b4b001.js";import{r as v}from"./assets/open-exercises-modal-427d9c7f.js";const x="current-exercises-filter-page",E="current-exercises-filter-keyword",m="current-exercises-group-name",u="is-opened-exercises-list",p="current-exercises-page",f="current-exercises-keyword",i={checkIsOpenExercisesList:()=>sessionStorage.getItem(u)==="true",openExercisesList:()=>{sessionStorage.setItem(u,"true")},closeExercisesList:()=>{sessionStorage.setItem(u,"false")},exercisesFilters:{set:e=>{sessionStorage.setItem(E,e)},get:()=>sessionStorage.getItem(E)??"Muscles"},exercisesGroups:{set:e=>{sessionStorage.setItem(m,e)},get:()=>sessionStorage.getItem(m)??""},exercisesFiltersTable:{setPage:e=>{sessionStorage.setItem(x,e.toString())},getPage:()=>{const e=sessionStorage.getItem(x);return e?Number(e):1}},exercisesTable:{setPage:e=>{sessionStorage.setItem(p,e.toString())},getPage:()=>{const e=sessionStorage.getItem(p);return e?Number(e):1},setKeyword:e=>{sessionStorage.setItem(f,e)},getKeyword:()=>sessionStorage.getItem(f)??""}},T=()=>{i.openExercisesList(),r.exercisesFiltersList.classList.add("visually-hidden"),r.exercisesFiltersPagination.classList.add("visually-hidden"),r.searchFormElement.classList.remove("visually-hidden"),r.exercisesContainer.classList.remove("visually-hidden")},F=()=>{i.closeExercisesList(),r.exercisesFiltersList.classList.remove("visually-hidden"),r.exercisesFiltersPagination.classList.remove("visually-hidden"),r.searchFormElement.classList.add("visually-hidden"),r.exercisesContainer.classList.add("visually-hidden")},_=i.checkIsOpenExercisesList();_?T():F();const S=({page:e,filter:s})=>L.get(`/filters?page=${e}&filter=${s}`),R=i.exercisesFiltersTable.getPage(),w=i.exercisesFilters.get();y({page:R,filter:w});r.exercisesFiltersTabsList.forEach(e=>{e.textContent.trim()===w&&e.classList.add("active")});function y({page:e,filter:s}){S({page:e,filter:s}).then(({data:{results:t,page:a,perPage:n,totalPages:o}})=>{new b("exercises-filters-pagination",{page:Number(a),itemsPerPage:n,totalItems:o*n}).on("beforeMove",function(l){const d=i.exercisesFilters.get();$(d,l.page),i.exercisesFiltersTable.setPage(l.page)}),C(t)})}function $(e,s){S({page:s,filter:e}).then(({data:t})=>{C(t.results),N()})}function C(e){r.exercisesFiltersList.innerHTML="";const s=e.map(({filter:t,name:a,imgURL:n})=>{const o=`data-filter="${t}"`,c=`data-group="${a}"`;return`
  <li class="filters__item" ${o} ${c}>
    <img class="filters__img-first" src="${n}"  ${o} ${c}></img>
    <div class="filters__wrapper-first" ${o}${c}>
    <h2 class="filters__title-first" ${o} ${c}>${a}</h2>
    <p class="filters__text-first" ${o} ${c}>${t}</p>
    </div>
  </li>
    `}).join("");r.exercisesFiltersList.insertAdjacentHTML("beforeend",s)}r.exercisesFiltersTabs.addEventListener("click",e=>{r.exercisesFiltersTabsList.forEach(t=>{t.classList.remove("active")}),e.target.classList.add("active");const s=e.target.textContent.trim();r.exercisesFiltersList.innerHTML="",F(),i.exercisesFilters.set(s),i.exercisesFiltersTable.setPage(1),y({page:1,filter:s})});function N(){window.scrollTo({top:830,behavior:"auto"})}const I=({filter:e,group:s,keyword:t="",page:a=1})=>{let n=new URLSearchParams({[e]:s,keyword:t,page:a,limit:10});return L.get(`/exercises?${n}`)},k=(e,{page:s,perPage:t,totalPages:a},n)=>{new b(e,{page:Number(s),itemsPerPage:t,totalItems:a*t}).on("beforeMove",function(c){n(c.page)})};function h(e,s,t){e.innerText=s,t&&(t.style.visibility="visible")}async function g(){let e=i.exercisesFilters.get(),s=i.exercisesGroups.get();e=e.toLowerCase().split(" ").join(""),e==="bodyparts"&&(e=e.slice(0,-1)),s=s.toLowerCase();const t=i.exercisesTable.getPage(),a=i.exercisesTable.getKeyword(),n=await I({filter:e,group:s,page:t,keyword:a});h(r.breadcrumbsText,s,r.breadcrumbsDivider);const{results:o,page:c,perPage:l,totalPages:d}=n.data;v(r.exercisesContainer,o),k("main-exercises-pagination",{page:c,perPage:l,totalPages:d},P=>{i.exercisesTable.setPage(P),g()})}g();async function K(e){e.preventDefault();let s=i.exercisesFilters.get().toLowerCase(),t=i.exercisesGroups.get().toLowerCase();s=s.toLowerCase().split(" ").join(""),s==="bodyparts"&&(s=s.slice(0,-1)),t=t.toLowerCase();const a=e.currentTarget.elements.search.value.trim().toLowerCase()??"";i.exercisesTable.setKeyword(a),i.exercisesTable.setPage(1),g()}function G(e){if(e.value){e.value="";return}}r.searchClearButton.addEventListener("click",e=>{G(r.searchInputElement),i.exercisesTable.setKeyword(""),i.exercisesTable.setPage(1),g()});r.searchFormElement.addEventListener("submit",e=>{K(e)});async function D(e,s,t){const a=await I({filter:s,group:t});h(r.breadcrumbsText,t,r.breadcrumbsDivider),v(e,a.data.results)}r.exercisesFiltersList.addEventListener("click",e=>{let s=e.target.dataset.filter,t=e.target.dataset.group;s=s.toLowerCase().split(" ").join(""),s==="bodyparts"&&(s=s.slice(0,-1)),t=t.toLowerCase(),s&&t&&(T(),i.exercisesGroups.set(t),D(r.exercisesContainer,s,t))});document.addEventListener("DOMContentLoaded",()=>{const e=i.exercisesTable.getKeyword();r.searchInputElement.value=e??""});
//# sourceMappingURL=commonHelpers2.js.map
